### ISSUE TITLE
Allow environment variables to be defined in snapx.yml

### ISSUE THREAD

**Issue by peters** [fintermobilityas/snapx#316]
By supporting environment variables in the snapx.yml file, the application will be able to read and use those environment variables when it is started.

```yml
environment:
  var1: value1
  var2: value2
  var3: value3
```
